    create table psicologo (
       id bigint generated by default as identity,
        description varchar(250),
        idade integer not null check (score>=1),
        documento integer not null,
        setor varchar(255), 
        nome varchar(255),
        primary key (id)
    );

INSERT INTO PSICOLOGO (name, description, idade, documento, setor)
VALUES ('Alberto', 'Psicológo formada na PUC', 25, 2365, 'Privado');
