    create table psicologo (
       id bigint generated by default as identity,
        description varchar(250),
        idade integer not null check (score>=1),
        documento integer not null,
        setor varchar(255), 
        nome varchar(255),
        estado varchar(255),
        primary key (id)
    );


INSERT INTO PSICOLOGO (name, description, idade, documento, setor)
VALUES ('Alberto', 'Psicológo formada na PUC', 25, 2365, 'Privado', 'SP');



    create table exercicio (
       id bigint generated by default as identity,
        score integer not null check (score>=1),
        status integer not null,
        dsExercicio varchar(255), 
        nmExercicio varchar(255),
        primary key (id)
    );


INSERT INTO EXERCICIO (nmExercicio, dsExercicio, score, status)
VALUES ('Respiração', 'Inspire fundo o máximo que conseguir, conte até 10 e expire.', 100, 0);

    create table clinicas (
       id bigint generated by default as identity,
        localizacao varchar(255),
        telefone varchar(255),
        name varchar(255), 
        descricao varchar(255),
        primary key (id)
    );

INSERT INTO CLINICAS (name, localizacao, descricao, telefone)
VALUES ('CLIA', 'Rua Vitória Régia, 1095 Santo André - SP', 'A CLIA Psicologia, Saúde & Educação em Santo André, oferece uma estrutura que atende às considerações acima.', 
            '(11) 953288942');
